(() => {
  "use strict";

  const $ = (id) => document.getElementById(id);
  const state = { cityData: null, taxPolicy: null, bonusTaxMode: "auto", detailView: "monthly" };
  const DEFAULTS = { city:"beijing",salary:50000,bonusInputMode:"months",bonusMonths:3,bonusAmount:150000,bonusMonth:12,bonusTaxMode:"auto",socialBaseMode:"auto",fundBaseMode:"auto",fundRateMode:"default",newSalary:60000,newBonusInputMode:"months",newBonusMonths:4,newBonusAmount:240000 };

  const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
  const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  const round2=v=>Math.round((v+Number.EPSILON)*100)/100;
  function money(v,signed=false){const x=Math.abs(round2(v));const f=new Intl.NumberFormat("zh-CN",{minimumFractionDigits:x%1?2:0,maximumFractionDigits:2}).format(x);if(signed){if(v>0)return `+¥${f}`;if(v<0)return `-¥${f}`;}return `${v<0?"-":""}¥${f}`;}
  function pct(v,signed=false){if(!Number.isFinite(v))return "—";const p=v*100;return `${signed&&p>0?"+":""}${p.toFixed(1)}%`;}
  function rateText(v){const p=v*100;return `${Number.isInteger(p)?p.toFixed(0):p.toFixed(1)}%`;}
  function currentCity(){return state.cityData.cities.find(c=>c.id===$("city").value)||state.cityData.cities[0];}
  function bonusValue(prefix=""){const isNew=prefix==="new";const salary=n($(isNew?"newSalary":"salary").value);const mode=$(isNew?"newBonusInputMode":"bonusInputMode").value;return mode==="months"?Math.max(0,salary*n($(isNew?"newBonusMonths":"bonusMonths").value)):Math.max(0,n($(isNew?"newBonusAmount":"bonusAmount").value));}
  function bracketTax(taxable,brackets,maxKey){const x=Math.max(0,taxable);const row=brackets.find(b=>b[maxKey]==null||x<=b[maxKey])||brackets[brackets.length-1];return Math.max(0,round2(x*row.rate-row.quick));}
  const comprehensiveTax=taxable=>bracketTax(taxable,state.taxPolicy.comprehensiveBrackets,"max");
  function separateBonusTax(bonus){if(bonus<=0)return 0;const m=bonus/12;const row=state.taxPolicy.bonusBrackets.find(b=>b.monthlyMax==null||m<=b.monthlyMax)||state.taxPolicy.bonusBrackets.at(-1);return Math.max(0,round2(bonus*row.rate-row.quick));}

  function getBaseSettings(salary,city){const socialRaw=$("socialBaseMode").value==="custom"?n($("socialBaseCustom").value,salary):salary;const fundRaw=$("fundBaseMode").value==="custom"?n($("fundBaseCustom").value,salary):salary;const f=city.housingFund;let personalFundRate=f.defaultPersonalRate,employerFundRate=f.defaultEmployerRate;if($("fundRateMode").value==="custom"){personalFundRate=n($("personalFundRate").value)/100;employerFundRate=n($("employerFundRate").value)/100;}return{socialRaw,fundRaw,personalFundRate,employerFundRate};}
  function calculateContributions(salary,city){const s=getBaseSettings(salary,city),items={};let personalSocial=0;for(const [key,row] of Object.entries(city.socialInsurance)){const base=clamp(s.socialRaw,row.baseMin,row.baseMax);const personal=round2(base*row.personalRate+(row.fixedPersonal||0));items[key]={...row,base,personal};personalSocial+=personal;}const f=city.housingFund;const fundBase=clamp(s.fundRaw,f.baseMin,f.baseMax);const personalFund=round2(fundBase*s.personalFundRate),employerFund=round2(fundBase*s.employerFundRate);return{items,socialRaw:s.socialRaw,fundRaw:s.fundRaw,personalSocial:round2(personalSocial),fundBase,personalFund,employerFund,totalFund:round2(personalFund+employerFund),personalFundRate:s.personalFundRate,employerFundRate:s.employerFundRate};}

  function deductionSelection(){const monthly={},annual={};let monthlyTotal=0,annualOnlyTotal=0;for(const [key,def] of Object.entries(state.taxPolicy.deductionDefaults)){const check=$(`deduction-${key}`),input=$(`deduction-amount-${key}`);if(!check||!check.checked)continue;const raw=Math.max(0,n(input.value));if(def.kind==="monthly"){let amount=raw;if(key==="personalPension")amount=Math.min(amount,(def.annualMax||12000)/12);monthly[key]=amount;monthlyTotal+=amount;}else{let amount=raw;if(def.annualMax)amount=Math.min(amount,def.annualMax);annual[key]=amount;annualOnlyTotal+=amount;}}return{monthly,annual,monthlyTotal:round2(monthlyTotal),annualOnlyTotal:round2(annualOnlyTotal),annualTotal:round2(monthlyTotal*12+annualOnlyTotal)};}

  function calculatePlan({salary,bonus,bonusMonth,mode,city}){salary=Math.max(0,salary);bonus=Math.max(0,bonus);bonusMonth=clamp(Math.round(bonusMonth),1,12);const contributions=calculateContributions(salary,city),deductions=deductionSelection();let cumulativePayrollGross=0,cumulativeWithheldPayroll=0,totalWithheld=0,cumulativeCash=0;const rows=[];const bonusSeparate=mode==="separate"?separateBonusTax(bonus):0;
    for(let month=1;month<=12;month++){const bonusThisMonth=month===bonusMonth?bonus:0;const mergedBonusThisMonth=mode==="merged"?bonusThisMonth:0;cumulativePayrollGross+=salary+mergedBonusThisMonth;const cumulativeTaxable=Math.max(0,cumulativePayrollGross-state.taxPolicy.monthlyBasicDeduction*month-contributions.personalSocial*month-contributions.personalFund*month-deductions.monthlyTotal*month);const targetCumulativeTax=comprehensiveTax(cumulativeTaxable);const payrollTaxThisMonth=Math.max(0,round2(targetCumulativeTax-cumulativeWithheldPayroll));cumulativeWithheldPayroll=round2(cumulativeWithheldPayroll+payrollTaxThisMonth);const bonusTaxThisMonth=mode==="separate"&&month===bonusMonth?bonusSeparate:0;const taxThisMonth=round2(payrollTaxThisMonth+bonusTaxThisMonth);totalWithheld=round2(totalWithheld+taxThisMonth);const cash=round2(salary+bonusThisMonth-contributions.personalSocial-contributions.personalFund-taxThisMonth);cumulativeCash=round2(cumulativeCash+cash);rows.push({month,salary,bonus:bonusThisMonth,pension:contributions.items.pension.personal,medical:contributions.items.medical.personal,unemployment:contributions.items.unemployment.personal,personalFund:contributions.personalFund,tax:taxThisMonth,cash,fundTotal:contributions.totalFund,cumulativeCash});}
    const salaryTaxableAnnual=Math.max(0,salary*12-state.taxPolicy.annualBasicDeduction-contributions.personalSocial*12-contributions.personalFund*12-deductions.annualTotal);let finalTax;if(mode==="separate")finalTax=round2(comprehensiveTax(salaryTaxableAnnual)+bonusSeparate);else finalTax=comprehensiveTax(Math.max(0,salaryTaxableAnnual+bonus));const settlement=round2(totalWithheld-finalTax),grossAnnual=round2(salary*12+bonus),annualCash=round2(cumulativeCash+settlement),personalFundAnnual=round2(contributions.personalFund*12),employerFundAnnual=round2(contributions.employerFund*12),fundTotalAnnual=round2(contributions.totalFund*12),socialAnnual=round2(contributions.personalSocial*12),comprehensiveAnnual=round2(annualCash+fundTotalAnnual);return{mode,salary,bonus,grossAnnual,annualCash,finalTax,settlement,totalWithheld,rows,contributions,deductions,personalFundAnnual,employerFundAnnual,fundTotalAnnual,socialAnnual,comprehensiveAnnual,cashRate:grossAnnual?annualCash/grossAnnual:0,comprehensiveRate:grossAnnual?comprehensiveAnnual/grossAnnual:0,separateBonusTax:bonusSeparate};}
  function chooseResults(salary,bonus,city){const args={salary,bonus,bonusMonth:n($("bonusMonth").value,12),city};const separate=calculatePlan({...args,mode:"separate"}),merged=calculatePlan({...args,mode:"merged"}),recommended=separate.annualCash>=merged.annualCash?separate:merged;let selected=recommended;if(state.bonusTaxMode==="separate")selected=separate;if(state.bonusTaxMode==="merged")selected=merged;return{separate,merged,recommended,selected};}

  function renderCityPolicy(city,c){const labels=state.cityData.statusLegend;$("policyStatus").textContent=labels[city.status]||city.status;$("policyStatus").className=`status-chip ${city.status}`;$("policySummary").textContent=`${city.name} · ${city.note}`;$("fundDefaultRate").textContent=`个人 ${rateText(city.housingFund.defaultPersonalRate)} · 公司 ${rateText(city.housingFund.defaultEmployerRate)}`;$("fundRateHint").textContent=city.housingFund.note;const rows=[];for(const item of Object.values(c.items))rows.push(`<tr><td>${item.label}</td><td>${money(item.baseMin)} ~ ${money(item.baseMax)}</td><td>${money(item.base)}</td><td>${rateText(item.personalRate)}${item.fixedPersonal?` + ${money(item.fixedPersonal)}`:""}</td><td>${money(item.personal)}</td><td>—</td></tr>`);rows.push(`<tr><td><b>住房公积金</b></td><td>${money(city.housingFund.baseMin)} ~ ${money(city.housingFund.baseMax)}</td><td>${money(c.fundBase)}</td><td>${rateText(c.personalFundRate)}</td><td>${money(c.personalFund)}</td><td>${money(c.employerFund)} (${rateText(c.employerFundRate)})</td></tr>`);$("contributionBody").innerHTML=rows.join("");$("monthlySocial").textContent=money(c.personalSocial);$("monthlyPersonalFund").textContent=money(c.personalFund);$("monthlyEmployerFund").textContent=money(c.employerFund);$("monthlyFundTotal").textContent=money(c.totalFund);const salary=n($("salary").value),messages=[];if($("fundBaseMode").value==="auto"&&(salary<city.housingFund.baseMin||salary>city.housingFund.baseMax))messages.push(`公积金实际计费基数为 ${money(c.fundBase)}。`);messages.push("自动基数按月工资估算；实际单位申报通常依据本人上年度月平均工资，可手工覆盖。 ");$("baseHint").textContent=messages.join(" ");}
  function renderMetrics(r){$("grossAnnual").textContent=money(r.grossAnnual);$("annualCash").textContent=money(r.annualCash);$("personalFundAnnual").textContent=money(r.personalFundAnnual);$("employerFundAnnual").textContent=money(r.employerFundAnnual);$("fundTotalAnnual").textContent=money(r.fundTotalAnnual);$("socialAnnual").textContent=money(r.socialAnnual);$("annualTax").textContent=money(r.finalTax);$("comprehensiveAnnual").textContent=money(r.comprehensiveAnnual);$("cashRate").textContent=pct(r.cashRate);$("comprehensiveRate").textContent=pct(r.comprehensiveRate);const s=r.settlement,el=$("settlement");el.textContent=s>0?`预计退税 ${money(s)}`:s<0?`预计补税 ${money(-s)}`:"¥0";el.className=s>0?"positive":s<0?"negative":"";const modeName=r.mode==="separate"?"年终奖单独计税":"奖金并入综合所得";$("selectedModeText").textContent=state.bonusTaxMode==="auto"?`自动择优：${modeName}`:`当前选择：${modeName}`;}
  function renderBonusComparison(results){const diff=round2(Math.abs(results.separate.annualCash-results.merged.annualCash)),recommendedMode=results.recommended.mode,selectedMode=results.selected.mode;const card=(r,title)=>{const recommended=r.mode===recommendedMode,selected=r.mode===selectedMode,bonusTaxText=r.mode==="separate"?money(r.separateBonusTax):"并入累计预扣";return `<div class="bonus-option ${recommended?"recommended":""} ${selected?"selected":""}">${recommended?`<span class="ribbon">推荐 · 多到手 ${money(diff)}</span>`:""}<h3>${title}</h3><div class="cash">${money(r.annualCash)}</div><dl><dt>年度最终税后现金</dt><dd>${money(r.annualCash)}</dd><dt>全年最终个税</dt><dd>${money(r.finalTax)}</dd><dt>年终奖计税</dt><dd>${bonusTaxText}</dd><dt>现金 + 公积金</dt><dd>${money(r.comprehensiveAnnual)}</dd></dl></div>`;};$("bonusComparison").innerHTML=card(results.separate,"全年一次性奖金单独计税")+card(results.merged,"奖金并入综合所得");}
  function renderMonthly(r){const rows=r.rows.map(x=>`<tr><td>${x.month} 月</td><td>${money(x.salary)}</td><td>${x.bonus?money(x.bonus):"—"}</td><td>${money(x.pension)}</td><td>${money(x.medical)}</td><td>${money(x.unemployment)}</td><td>${money(x.personalFund)}</td><td>${money(x.tax)}</td><td><b>${money(x.cash)}</b></td><td>${money(x.fundTotal)}</td><td>${money(x.cumulativeCash)}</td></tr>`);if(Math.abs(r.settlement)>=.01)rows.push(`<tr><td><b>年度汇算</b></td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td class="${r.settlement>0?"positive":"negative"}">${r.settlement>0?"退税 "+money(r.settlement):"补税 "+money(-r.settlement)}</td><td><b>${money(r.settlement)}</b></td><td>—</td><td><b>${money(r.annualCash)}</b></td></tr>`);$("monthlyBody").innerHTML=rows.join("");}
  function renderAnnual(r){const items=[["工资收入",r.salary*12],["年终奖",r.bonus],["税前总收入",r.grossAnnual],["个人养老保险",r.contributions.items.pension.personal*12],["个人医疗保险",r.contributions.items.medical.personal*12],["个人失业保险",r.contributions.items.unemployment.personal*12],["个人社保合计",r.socialAnnual],["个人公积金",r.personalFundAnnual],["公司公积金",r.employerFundAnnual],["专项/其他税前扣除",r.deductions.annualTotal],["全年最终个税",r.finalTax],["发薪阶段已预扣税",r.totalWithheld],["年度汇算退/补税",r.settlement],["年度最终税后现金",r.annualCash],["公积金账户全年入账",r.fundTotalAnnual],["现金 + 公积金",r.comprehensiveAnnual]];$("annualList").innerHTML=items.map(([label,value])=>`<div class="annual-row"><span>${label}</span><b>${money(value,label==="年度汇算退/补税")}</b></div>`).join("");}
  function increase(a,b){if(b===0)return a===0?0:NaN;return(a-b)/b;}
  function renderPlanComparison(cur,next){const cashInc=increase(next.annualCash,cur.annualCash),fundInc=increase(next.fundTotalAnnual,cur.fundTotalAnnual),totalInc=increase(next.comprehensiveAnnual,cur.comprehensiveAnnual);$("cashIncrease").textContent=pct(cashInc,true);$("fundIncrease").textContent=pct(fundInc,true);$("totalIncrease").textContent=pct(totalInc,true);const rows=[["税前年收入","grossAnnual"],["年度最终税后现金","annualCash"],["公积金账户入账","fundTotalAnnual"],["个人社保","socialAnnual"],["全年个税","finalTax"],["现金 + 公积金","comprehensiveAnnual"]];$("planComparisonBody").innerHTML=rows.map(([label,key])=>{const delta=round2(next[key]-cur[key]),ratio=increase(next[key],cur[key]);return `<tr><td>${label}</td><td>${money(cur[key])}</td><td>${money(next[key])}</td><td>${money(delta,true)}</td><td class="${ratio>=0?"positive":"negative"}">${pct(ratio,true)}</td></tr>`;}).join("");}
  function renderDeductions(){const defs=state.taxPolicy.deductionDefaults;$("deductionGrid").innerHTML=Object.entries(defs).map(([key,def])=>{const val=def.kind==="monthly"?def.monthly:def.annual,unit=def.kind==="monthly"?"/月":"/年";return `<div class="deduction-item"><input id="deduction-${key}" type="checkbox"><label for="deduction-${key}">${def.label}</label><div class="amount-wrap"><input id="deduction-amount-${key}" type="number" min="0" step="100" value="${val||0}"><span class="unit">${unit}</span></div></div>`;}).join("");Object.keys(defs).forEach(key=>{$(`deduction-${key}`).addEventListener("change",()=>{if(key==="housingLoan"&&$(`deduction-${key}`).checked)$("deduction-rent").checked=false;if(key==="rent"&&$(`deduction-${key}`).checked)$("deduction-housingLoan").checked=false;update();});$(`deduction-amount-${key}`).addEventListener("input",update);});}
  function updateVisibility(){const b=$("bonusInputMode").value;$("bonusMonthsWrap").classList.toggle("hidden",b!=="months");$("bonusAmountWrap").classList.toggle("hidden",b!=="amount");const nb=$("newBonusInputMode").value;$("newBonusMonthsWrap").classList.toggle("hidden",nb!=="months");$("newBonusAmountWrap").classList.toggle("hidden",nb!=="amount");$("socialBaseCustomWrap").classList.toggle("hidden",$("socialBaseMode").value!=="custom");$("fundBaseCustomWrap").classList.toggle("hidden",$("fundBaseMode").value!=="custom");const cf=$("fundRateMode").value==="custom";$("fundDefaultLine").classList.toggle("hidden",cf);$("fundCustomPanel").classList.toggle("hidden",!cf);}
  function update(){if(!state.cityData||!state.taxPolicy)return;updateVisibility();const city=currentCity(),salary=Math.max(0,n($("salary").value)),bonus=bonusValue(""),results=chooseResults(salary,bonus,city);renderCityPolicy(city,results.selected.contributions);renderMetrics(results.selected);renderBonusComparison(results);renderMonthly(results.selected);renderAnnual(results.selected);const newSalary=Math.max(0,n($("newSalary").value)),newBonus=bonusValue("new"),args={salary:newSalary,bonus:newBonus,bonusMonth:n($("bonusMonth").value,12),city},ns=calculatePlan({...args,mode:"separate"}),nm=calculatePlan({...args,mode:"merged"});let next=state.bonusTaxMode==="separate"?ns:state.bonusTaxMode==="merged"?nm:(ns.annualCash>=nm.annualCash?ns:nm);renderPlanComparison(results.selected,next);}
  function syncFundCustomDefaults(){const c=currentCity();$("personalFundRate").value=(c.housingFund.defaultPersonalRate*100).toFixed(1).replace(".0","");$("employerFundRate").value=(c.housingFund.defaultEmployerRate*100).toFixed(1).replace(".0","");}
  function reset(){Object.entries(DEFAULTS).forEach(([k,v])=>{if($(k))$(k).value=v;});state.bonusTaxMode="auto";document.querySelectorAll("#bonusTaxMode button").forEach(b=>b.classList.toggle("active",b.dataset.value===state.bonusTaxMode));Object.keys(state.taxPolicy.deductionDefaults).forEach(key=>$(`deduction-${key}`).checked=false);$("socialBaseCustom").value=DEFAULTS.salary;$("fundBaseCustom").value=DEFAULTS.salary;syncFundCustomDefaults();update();}
  function bindEvents(){["salary","bonusInputMode","bonusMonths","bonusAmount","bonusMonth","socialBaseMode","socialBaseCustom","fundBaseMode","fundBaseCustom","fundRateMode","personalFundRate","employerFundRate","newSalary","newBonusInputMode","newBonusMonths","newBonusAmount"].forEach(id=>$(id).addEventListener($(id).tagName==="SELECT"?"change":"input",update));$("city").addEventListener("change",()=>{syncFundCustomDefaults();update();});$("bonusTaxMode").addEventListener("click",e=>{const btn=e.target.closest("button[data-value]");if(!btn)return;state.bonusTaxMode=btn.dataset.value;document.querySelectorAll("#bonusTaxMode button").forEach(b=>b.classList.toggle("active",b===btn));update();});$("detailTabs").addEventListener("click",e=>{const btn=e.target.closest("button[data-value]");if(!btn)return;state.detailView=btn.dataset.value;document.querySelectorAll("#detailTabs button").forEach(b=>b.classList.toggle("active",b===btn));$("monthlyPanel").classList.toggle("hidden",state.detailView!=="monthly");$("annualPanel").classList.toggle("hidden",state.detailView!=="annual");});$("resetBtn").addEventListener("click",reset);}
  async function init(){try{const [cr,tr]=await Promise.all([fetch("./data/city-policies.json"),fetch("./data/tax-policy.json")]);if(!cr.ok||!tr.ok)throw new Error("policy data load failed");state.cityData=await cr.json();state.taxPolicy=await tr.json();$("city").innerHTML=state.cityData.cities.sort((a,b)=>a.rank-b.rank).map(c=>`<option value="${c.id}">${c.rank}. ${c.name}</option>`).join("");for(let i=1;i<=12;i++)$("bonusMonth").insertAdjacentHTML("beforeend",`<option value="${i}">${i} 月</option>`);$("dataBadge").textContent=`政策快照 ${state.cityData.snapshotDate} · GDP 前30城市 · 当前快照全年估算`;$("sourceFooter").textContent=`城市政策数据快照：${state.cityData.snapshotDate}。页面按当前有效/暂行/最近一期公开值静态计算，不按年内月份分段；详细核验记录见仓库 DATA_SOURCES.md。`;renderDeductions();bindEvents();reset();}catch(err){console.error(err);$("dataBadge").textContent="政策数据加载失败，请刷新页面";}}
  init();
})();
